CREATE OR REPLACE PACKAGE PKG_ADMIN AS

TYPE REF_CURSOR IS REF CURSOR;
FUNCTION getAdmPrd RETURN REF_CURSOR;
FUNCTION getAdmPrd(ADMPRD_KEY NUMBER) RETURN REF_CURSOR;
FUNCTION getAdmPrd(ADMPRD_ARRAY STRING_ARRAY) RETURN REF_CURSOR;
FUNCTION insertAdmPrd(ADM_PRD_VAR ADM_PRD_T) RETURN NUMBER;
FUNCTION updateAdmPrd(ADM_PRD_VAR ADM_PRD_T) RETURN NUMBER;
FUNCTION deleteAdmPrd(ADM_PRD_KEY NUMBER) RETURN NUMBER;

END PKG_ADMIN;
/

CREATE OR REPLACE PACKAGE BODY PKG_ADMIN AS

FUNCTION getAdmPrd RETURN REF_CURSOR
AS LANGUAGE JAVA NAME 'AdmPrd.getAdmPrd() return java.sql.ResultSet';
FUNCTION getAdmPrd(ADMPRD_KEY NUMBER) RETURN REF_CURSOR
AS LANGUAGE JAVA NAME 'AdmPrd.getAdmPrd(int) return java.sql.ResultSet';
FUNCTION getAdmPrd(ADMPRD_ARRAY STRING_ARRAY) RETURN REF_CURSOR
AS LANGUAGE JAVA NAME 'AdmPrd.getAdmPrd(oracle.sql.ARRAY) return java.sql.ResultSet';
FUNCTION insertAdmPrd(ADM_PRD_VAR ADM_PRD_T) RETURN NUMBER
AS LANGUAGE JAVA NAME 'AdmPrd.insertAdmPrd(oracle.sql.STRUCT) return long';
FUNCTION updateAdmPrd(ADM_PRD_VAR ADM_PRD_T) RETURN NUMBER
AS LANGUAGE JAVA NAME 'AdmPrd.updateAdmPrd(oracle.sql.STRUCT) return long';
FUNCTION deleteAdmPrd(ADM_PRD_KEY NUMBER) RETURN NUMBER
AS LANGUAGE JAVA NAME 'AdmPrd.deleteAdmPrd(int) return int';

END PKG_ADMIN;
/